### ISSUE TITLE
There is a varying margin between option buttons on screens with different dpi.

### ISSUE THREAD

**Issue by mirzacharlie** [nambicompany/expandable-fab#10]
Could you please change the margin of the buttons from px to dp? Alternatively, please add an option like "firstFabOptionMarginPx" for the other option buttons.

**Comment by kabumere** [comment]
Hey @mirzacharlie,

    Could you please change the margin of the buttons from px to dp?
[getDimension](https://developer.android.com/reference/android/content/res/Resources#getDimension(int)) and [getDimensionPixelSize](https://developer.android.com/reference/android/content/res/Resources#getDimensionPixelSize(int)) methods of the Android SDK should help you convert DP to Pixels for use in the library. So you can retrieve your DP value and pass to one of the two methods above, and use the returned value when setting the margins.

    Alternatively, please add an option like "firstFabOptionMarginPx" for the other option buttons.
[firstFabOptionMarginPx](https://github.com/nambicompany/expandable-fab/blob/master/library/src/main/kotlin/com/nambimobile/widgets/efab/ExpandableFab.kt#L157) is the margin between the first FabOption and the ExpandableFab button only. To change the margins between the other FabOptions, use [successiveFabOptionMarginPx](https://github.com/nambicompany/expandable-fab/blob/master/library/src/main/kotlin/com/nambimobile/widgets/efab/ExpandableFab.kt#L172).

**Comment by mirzacharlie** [comment]
Hi, thx for your answer. This code works fine for me.

```
        val px = TypedValue.applyDimension(
            TypedValue.COMPLEX_UNIT_DIP,
            32f,
            resources.displayMetrics
        )
        fab.firstFabOptionMarginPx = px
        fab.successiveFabOptionMarginPx = px
```
