### ISSUE TITLE
Two float button on once screen

### ISSUE THREAD

**Issue by Leeeeerich** [nambicompany/expandable-fab#14]
Hi! I have a question, we may add two fab on one screen, how in image: 
![Untitled](https://user-images.githubusercontent.com/26391015/105181565-a20b2b00-5b34-11eb-8c87-a499963ec020.png)

**Comment by kabumere** [comment]
Hey @Leeeeerich,

That screenshot can be replicated by using multiple ExpandableFabs, with one of them being in a BottomAppBar.

Our example app shows how to achieve both (albeit separately):

ExpandableFab within a BottomAppBar:
https://github.com/nambicompany/expandable-fab/blob/master/examples/src/main/res/layout/bottom_app_bar_compatibility_fragment.xml

Multiple ExpandableFabs on screen:
https://github.com/nambicompany/expandable-fab/blob/master/examples/src/main/res/layout/multiple_expandablefabs_fragment.xml

You should be able to combine the relevant pieces of the two layout files above to achieve what you're looking for. You can also run the example app to see those layout files in action.

Let me know if you still need help after reviewing those.

**Comment by kabumere** [comment]
Hey @Leeeeerich,

Did the above solution work for you?

**Comment by Leeeeerich** [comment]
Oh, sorry! Yeah, it work for me. I close it, thanks!
