### ISSUE TITLE
How change speed animation

### ISSUE THREAD

**Issue by Leeeeerich** [nambicompany/expandable-fab#15]
Hi! How I speed up the animation?

I use:

`app:efab_openingAnimationDurationMs="100"
 app:efab_closingAnimationDurationMs="100"`

but this only works on the first opening, on the second and subsequent ones, the animation speed returns to the initial one. I tried to install both through the markup and programmatically.

**Comment by kabumere** [comment]
Hey @Leeeeerich,

The animation durations and properties can be set on each of the individual Views. I have linked to some relevant properties below that should help you, but please view the [JavaDoc](https://nambicompany.github.io/expandable-fab/javadoc/v1/index.html) or [KDoc](https://nambicompany.github.io/expandable-fab/kdoc/v1/library/com.nambimobile.widgets.efab/index.html) for each class in the library, as properties other than those listed below can indirectly affect animations as well (for instance, the translationX value of a `Label` will determine how far it travels horizontally during animations). The documentation should explain exactly what each property does and how it influences animations.

ExpandableFab:
[Opening Animation Duration](https://nambicompany.github.io/expandable-fab/kdoc/v1/library/com.nambimobile.widgets.efab/-expandable-fab/opening-animation-duration-ms.html)
[Closing Animation Duration](https://nambicompany.github.io/expandable-fab/kdoc/v1/library/com.nambimobile.widgets.efab/-expandable-fab/closing-animation-duration-ms.html)
[Closing Anticipate Tension](
https://nambicompany.github.io/expandable-fab/kdoc/v1/library/com.nambimobile.widgets.efab/-expandable-fab/closing-anticipate-tension.html)

FabOption:
[Opening Animation Duration](https://nambicompany.github.io/expandable-fab/kdoc/v1/library/com.nambimobile.widgets.efab/-fab-option/opening-animation-duration-ms.html)
[Closing Animation Duration](https://nambicompany.github.io/expandable-fab/kdoc/v1/library/com.nambimobile.widgets.efab/-fab-option/closing-animation-duration-ms.html)
[Opening Overshoot Tension](https://nambicompany.github.io/expandable-fab/kdoc/v1/library/com.nambimobile.widgets.efab/-fab-option/opening-overshoot-tension.html)

Label:
[Hidden to Visible Animation Duration](https://nambicompany.github.io/expandable-fab/kdoc/v1/library/com.nambimobile.widgets.efab/-label/hidden-to-visible-animation-duration-ms.html)
[Visible to Hidden Animation Duration](https://nambicompany.github.io/expandable-fab/kdoc/v1/library/com.nambimobile.widgets.efab/-label/visible-to-hidden-animation-duration-ms.html)
[Overshoot Tension](https://nambicompany.github.io/expandable-fab/kdoc/v1/library/com.nambimobile.widgets.efab/-label/overshoot-tension.html)

**Comment by kabumere** [comment]
Hey @Leeeeerich,

Have the links above helped you?

**Comment by Leeeeerich** [comment]
Hey! Thanks. It is was very hard, but understand. Ok, if you need to speed up opening menu: `label_hiddenToVisibleAnimationDurationMs` and `fab_openingAnimationDurationMs`

My fab with open and close:

```
<com.nambimobile.widgets.efab.FabOption
                android:id="@+id/eFab"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                app:fab_openingAnimationDurationMs="25"
                app:fab_closingAnimationDurationMs="25"
                app:label_hiddenToVisibleAnimationDurationMs="75"
                app:label_visibleToHiddenAnimationDurationMs="75"
                app:fab_color="@android:color/white"
                app:fab_icon="@drawable/ic_post"
                app:fab_orientation="portrait"
                app:label_backgroundColor="@android:color/white"
                app:label_text="@string/post"
                app:label_textColor="@color/blackBlueColor" />
```
