### ISSUE TITLE
Transparent background for option label

### ISSUE THREAD

**Issue by DenShlk** [nambicompany/expandable-fab#21]
Hi there! Thanks for the beautiful view!

I'd like to make the label background transparent (to show only text), I tried to set "label_backgroundColor" to "android: transparent" (#0000), but it didn't work. 

I also tried to disable the label, but when I set the "label_text" empty, there is a still black rectangle. 

So, summing up, my ask is to add the ability to use transparent background for labels.

**Comment by kabumere** [comment]
Hey @DenShlk,

Thanks for bringing this issue to our attention. Please try the latest version `v1.1.1` now available on Maven Central (or clone the latest commits from the `master` branch on this repo). Please let me know if the latest update fixes your problem.

**Comment by DenShlk** [comment]
Hi! It fixed my issue, thanks for the quick update!
