### ISSUE TITLE
Gape between all fabs

### ISSUE THREAD

**Issue by ansh1503-xd** [nambicompany/expandable-fab#22]
I have taken 1 fab and 3 fabOptions but there is slight gape between all of them according to device screen resolution. Can u provide me the name of functionality so that I can reduce that margin or padding whatever

**Comment by kabumere** [comment]
Hey @ansh1503-xd,

I see you closed the ticket. Were you able to solve your issue?

If not, does [this answer](https://github.com/nambicompany/expandable-fab/issues/10#issuecomment-717334464) help you?
