### ISSUE TITLE
Let user scroll expandable fab when they add more than 5 Fab

### ISSUE THREAD

**Issue by Istiakshovon** [nambicompany/expandable-fab#26]
**Feature-Request** : 

![Expandable Fab](https://raw.githubusercontent.com/nambicompany/expandable-fab/master/docs/gallery/bottom_app_bar_compatibility.gif) 

Usually, your screen is too big and, if I add more than 20 FAB than, they might go outta screen. For that reason I want a scrollable feature

**Comment by kabumere** [comment]
Hey @Istiakshovon,

I'm not inclined to implement this feature at the moment. The ExpandableFab works best in drawing a user's attention and showcasing the most prominent actions of the given screen when there's only a few number of actions available to take. I've found that most times when people start adding 10 or more actions in the ExpandableFab, some of those actions would probably be better suited for a [Navigation Drawer](https://developer.android.com/guide/navigation/navigation-ui#add_a_navigation_drawer) or [Overflow/Options Menu](https://developer.android.com/guide/topics/ui/menus#options-menu).

If however you simply have a very complex screen that actually does have 20+ relevant actions for a user to take, I still think there are better ways to list those actions for the user. Twenty or more actions in a scrollable ExpandableFab seems like a terrible user experience, in my opinion. Depending on your UI, perhaps try listing these actions in a [Spinner](https://developer.android.com/guide/topics/ui/controls/spinner), [Dialog](https://developer.android.com/guide/topics/ui/dialogs), or scrollable [RecyclerView](https://developer.android.com/guide/topics/ui/layout/recyclerview). There are other premade Views available beyond those that can handle lists of items as well.

So closing this for now as a 'Will not Implement'. If anything changes in the future and this does get added to a future release, I'll let you know,

**Comment by Istiakshovon** [comment]
@kabumere  Thanks for your reply. Usually, I forgot about Navigation Drawer. And, also thanks for reminding me that... :)

**Comment by kabumere** [comment]
No problem @Istiakshovon! Thank you for using the library, and I hope it comes in handy for your future projects.
