### ISSUE TITLE
Bug with efabColor

### ISSUE THREAD

**Issue by skobelev-dmitriy** [nambicompany/expandable-fab#3]
Good day. When trying to use the efabColor, fabOptionColor properties programmatically, the color changes the first time, but then does not change. Also, after the first setting, the color is displayed incorrectly. I wrote through a translator :)
![Screenshot_1600285240](https://user-images.githubusercontent.com/11031637/93384599-3f0c3d80-f88f-11ea-8f1f-1a85bfda22a7.png)
![Screenshot_16002852402](https://user-images.githubusercontent.com/11031637/93385064-dec9cb80-f88f-11ea-8145-03d358a13f28.png)

**Comment by kabumere** [comment]
Hey @skobelev-dmitriy,

When setting the color properties like `efabColor` and `fabOptionColor`, you must pass an integer value in the form of `0xAARRGGBB`. 

You can easily do this by calling `ContextCompat.getColor(context, R.color.colorPrimary)`.

The documentation should be clearer, so sorry about that. Will update it now.

**Comment by kabumere** [comment]
Hey @skobelev-dmitriy,

Did the above comment solve your issue?

**Comment by skobelev-dmitriy** [comment]
> Hey @skobelev-dmitriy,
> 
> Did the above comment solve your issue?

Thanks, this is solve my issue
![Screenshot_1600398445](https://user-images.githubusercontent.com/11031637/93550951-d6a88380-f996-11ea-80f4-70e3475304db.png)
