### ISSUE TITLE
Load icon using url 

### ISSUE THREAD

**Issue by MohamedAbdelrazek** [nambicompany/expandable-fab#39]
How to load icon using url instead of res id

**Comment by kabumere** [comment]
Hey @MohamedAbdelrazek,

The library does not include any functionality to make network requests, as that's outside the scope of what it aims to accomplish.

There are plenty of well-tested image downloading and caching libraries out there for you to use however, like Picasso and Glide.

You could also simply download the image yourself then set the icon using APIs like HttpUrlConnection or a networking library like OkHttp.

**Comment by kabumere** [comment]
Im assuming you've already found a different way of downloading your preferred icon over the network, so I am closing this ticket. Feel free to open a new ticket if you have any other questions about the library.
