### ISSUE TITLE
Show method does not work

### ISSUE THREAD

**Issue by hannzern** [nambicompany/expandable-fab#4]
I am trying to programmatically toggle the show() and hide() methods but does not work unfortunately... The setEfabColor does work tho

**Comment by kabumere** [comment]
Hey @hannzern,

I see you closed this ticket. Did you solve the issue you were having?

**Comment by hannzern** [comment]
Yes I did, realized show() and hide() was actually just hiding and showing the ExpandableFab. Btw, is there a way to configure where the bottom animates to? For example for vertical, to expand toward the top direction (currently), and also a way to expand towards the bottom direction?

**Comment by kabumere** [comment]
@hannzern I believe you're looking for [fabOptionPosition](https://github.com/nambicompany/expandable-fab/blob/928b98e1284f49c8310fbfc1ccb9f419545405b4/library/src/main/kotlin/com/nambimobile/widgets/efab/ExpandableFab.kt#L150).

By default it's set to FabOptionPosition.ABOVE, but if you want the FabOptions to animate downwards, you can set it to FabOptionPosition.BELOW (you can set this via XML too).
