### ISSUE TITLE
Change speed of showing up options

### ISSUE THREAD

**Issue by jawegielewski** [nambicompany/expandable-fab#40]
Good job! I have a question. Is there a possibility to change speed of showing up options? What if I wanted to speed up the options showing up?

**Comment by kabumere** [comment]
Hey @jawegielewski,

[This answer](https://github.com/nambicompany/expandable-fab/issues/15#issuecomment-790741280) from a previous ticket should help you.

In addition to changing the speeds on the individual components from the above link, starting with v1.2.1 there are also global properties you can set on the `ExpandableFabLayout`. Setting the global properties will save you the trouble of having to set the animation duration of every single FabOption, Label, Overlay and ExpandableFab.

These new global properties can be seen [here](https://github.com/nambicompany/expandable-fab/blob/master/library/src/main/kotlin/com/nambimobile/widgets/efab/ExpandableFabLayout.kt#L87-L200), along with their documentation.

All of the fields mentioned can be set from both XML and programmatically in your code. Let me know if you have any other questions, and thanks for your kind words!

**Comment by kabumere** [comment]
Hey @jawegielewski,

Did the above answer help you with changing the speed of the FabOptions and Labels?

**Comment by jawegielewski** [comment]
Hey to be honest I abandoned this idea of using your classes as I change my project's design a bit. But thank you anyway :)

**Comment by kabumere** [comment]
Hey @jawegielewski,

No problem. The widget doesn't work for every project, but I hope you consider using it again for a future one. Happy coding!
