### ISSUE TITLE
Feature request: Add disable function

### ISSUE THREAD

**Issue by panafana** [nambicompany/expandable-fab#41]
It would be nice to have a disable function for the FAB to disable the animation and the menu of options from showing.
This is quite an edge case but it is helpful in the event that having or not having the FAB menu popup is not a fixed action and depends on something else.

**Comment by kabumere** [comment]
Hey @panafana,

Both the [ExpandableFab](https://github.com/nambicompany/expandable-fab/blob/master/library/src/main/kotlin/com/nambimobile/widgets/efab/ExpandableFab.kt#L102-L113) and [FabOptions](https://github.com/nambicompany/expandable-fab/blob/master/library/src/main/kotlin/com/nambimobile/widgets/efab/FabOption.kt#L76-L87) have properties that allow you to disable them. Is this what you're looking for?

**Comment by kabumere** [comment]
Hey @panafana,

I assume the links above helped you, so I'm closing the ticket. Feel free to reply if you still need help with disabling though.
