### ISSUE TITLE
position of extendable fabs

### ISSUE THREAD

**Issue by Adwooo** [nambicompany/expandable-fab#42]
![miniFabs](https://user-images.githubusercontent.com/32128526/144599813-f4bd7380-e223-4330-b6eb-7a9ecfb50e5e.png)

Hi
Is there a simple way to change position of efabs like on attached image?

**Comment by kabumere** [comment]
Hey @Adwooo,

Unfortunately that is not a valid [FabOptionPosition](https://github.com/nambicompany/expandable-fab/blob/master/library/src/main/kotlin/com/nambimobile/widgets/efab/FabOptionPosition.kt). Since FabOptions can be various sizes, I don't know if it's feasible to accomplish this (while ensuring that all FabOptions fit nicely in a circle).

I can mark it as a feature request and look into it though when planning for the next release.

**Comment by Adwooo** [comment]
Thank you. That would be great becouse to be honest that kind of setup loos może userfriendly then current. Super screen recorder has a simular future and i musi  say mits wquite?friendly smoking: ![Screenshot_20211203-232843_Gallery.jpg](https://user-images.githubusercontent.com/32128526/144681701-0c2eb447-a31f-45bd-ba49-5dc971c49fda.jpg)

When are you planning new relese?.

**Comment by kabumere** [comment]
Hey @Adwooo,

I think you used a translator that messed up some of your words, so it's hard to understand portions of what you said. However, I can reply to some of it:

1) 'Super Screen Recorder' ensures their FabOption equivalents are the correct size, so the layout fits. However, ourlibrary allows users to choose any custom size they want (like in [this gif](https://github.com/nambicompany/expandable-fab/blob/master/docs/gallery/custom_sizes.gif)), so if a developer uses very large sizes, that circular layout will break and look bad for end-users.
2) The next release of the library will likely come sometime in January 2022.

**Comment by Adwooo** [comment]
Sorry for those mistakes. Maybe positioning could use only base size of an option? Or up to some max size there you can use it? And max number of options? Becouse it can be hard to fit them if theres more then 5/6.

**Comment by kabumere** [comment]
Yeah, I'll consider all those options when I look into the feature request next month. No guarantee that it will make its way into the library, however.

**Comment by kabumere** [comment]
Closing the ticket, but keeping the feature request label on it so I remember to come back and evaluate.
